version: '3.7'

services:
  vpn:
    image: dockerhub.ir/bjddd192/shadowsocks-privoxy:2.9.1
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8118:8118"
      - "172.17.0.1:8118:8118"
